### ISSUE TITLE
Default Android indicator for SlidingMenu 

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/com.ninetwozero.bf4intel#1]
The Slidingmenu should use the default Android icon!

**Comment by karllindmark** [comment]
Addressed on Dev branch, however not exactly the same. We should probably try to use the "stock" drawer from Android compatibility package. :-)

**Comment by peter-budo** [comment]
Explain or drop some links not sure what you talking about

**Comment by karllindmark** [comment]
@peter-budo: https://github.com/karllindmark/com.ninetwozero.battlelog/issues/2
