### ISSUE TITLE
Project Dependency Status

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/com.ninetwozero.bf4intel#159]
# Hello world!

We've found updates to the following dependencies used in **ninetwozero/com.ninetwozero.bf4intel**:

File: core/build.gradle

**gson** 2.2.4--> 2.3
`"com.google.code.gson:gson:2.3"`

**junit** 4.11--> 4.12-beta-1
`"junit:junit:4.12-beta-1"`

File: BF4Intel/build.gradle

**library** 1.0.4--> 1.0.6
`"com.mcxiaoke.volley:library:1.0.6"`

**otto** 1.3.4--> 1.3.5
`"com.squareup:otto:1.3.5"`

**gson** 2.2.4--> 2.3
`"com.google.code.gson:gson:2.3"`

**picasso** 2.2.0--> 2.3.4
`"com.squareup.picasso:picasso:2.3.4"`

**sprinkles** 1.3.0--> 1.3.1
`"se.emilsjolander:sprinkles:1.3.1"`

_This list was generated via http://isyourprojectuptodate.com/_

**Comment by peter-budo** [comment]
When you create issue and then is solved you need to close it...
